### ISSUE TITLE
disable firewall?

### ISSUE THREAD

**Issue by y0d4a** [3gstudent/Use-COM-objects-to-bypass-UAC#1]
hi, i would like to try disabling firewall from regular user...
but in compile got:

> DisableFirewall.cpp
> DisableFirewall.cpp(589) : error C2061: syntax error : identifier '_TCHAR'
> DisableFirewall.cpp(591) : error C3861: '_T': identifier not found
> DisableFirewall.cpp(686) : error C2664: 'StringCchPrintfA' : cannot convert parameter 1 from 'WCHAR [300]' to 'STRSAFE_LPSTR'
>         Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

**Comment by 3gstudent** [comment]
You can use Visual Studio 2012 or newer to complie it.

**Comment by y0d4a** [comment]
this is for VS 2012 pro?

**Comment by 3gstudent** [comment]
Yes

**Comment by y0d4a** [comment]
i mean, i am using it :)

**Comment by y0d4a** [comment]
lol, you did not understand me :)
i mean, i have VS 2012 pro and was try to compile with him and got this error..

**Comment by 3gstudent** [comment]
Use Unicode Character Set.
See this:
https://stackoverflow.com/questions/9349342/about-the-character-set-option-in-visual-studio

**Comment by 3gstudent** [comment]
[ConsoleApplication1.zip](https://github.com/3gstudent/Use-COM-objects-to-bypass-UAC/files/3080134/ConsoleApplication1.zip)

Use this
